import numpy as np
from time import time
from scipy import stats
import random
import matplotlib.pyplot as plt

if __name__ == "__main__":
    #1.1 Does your RNG generate random numbers?
    randgen_1 = np.random.RandomState(1)
    list_random = []
    number = 10000
    for i in range(number):
        list_random.append(randgen_1.rand())

    hist, bins = np.histogram(list_random, bins=10)
    print "1.1 Does your RNG generate random numbers?"
    print "     There are %s numbers generated by RND." % number
    print "     This is the # of random numbers in each bins:"
    print "     %s" % hist
    print "#" * 75
    #1.2 How do you initialize the seed of your RNG?
    current_time = time()
    randgen_2 = np.random.RandomState(int(current_time))
    print "1.2 How do you initialize the seed of your RNG?"
    print "     This is the current time in int type: %s" % int(current_time)
    print "#" * 75

    #1.3 Generate two sequences of 1000000 numbers each, for every sequence use a different seed.
    #   Are these two sequences different? How do you know this?

    randgen1 = np.random.RandomState(1)
    randgen2 = np.random.RandomState(2)

    listA = randgen1.uniform(low=0.0, high=1.0, size=1000000)
    listB = randgen2.uniform(low=0.0, high=1.0, size=1000000)

    print "1.3 Generate two sequences of 1000000 numbers each, for every sequence use a different seed."
    print " Are these two sequences different? How do you know this?"
    A, B = stats.mstats.ttest_ind(listA, listB)
    print "The pvalue is %s, the t-statistics is %s" %(B, A)

